#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  4 17:55:48 2020

@author: bizzaro
"""

"""
Collatz Conjecture
"""
import numpy as np
trys = np.arange(0,5)
for i in range(len(trys)):
    



    number = int(input("number = "))


    evenoddnumber = number % 2
    print(evenoddnumber)

    if evenoddnumber == 0:                 #if number is even divide by 2
        newnumber = number/2
        print(newnumber)
    
    if evenoddnumber == 1:                 #if number is odd mulitply by 3 and add 1
        newnumber = (number*3)+1
        print(newnumber)

