#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct  9 12:28:04 2021

@author: bizzaro
"""
import magpylib as mag3
src1 = mag3.current.Circular(current=15, diameter=2)
src2 = mag3.misc.Dipole(moment=(100,100,100))
sens = mag3.Sensor(position=(1,1,1))
obs_pos = (1,2,3)

B = mag3.getB(sources=[src1,src2], observers=[sens,obs_pos]) 
print(B)

'''
The magnetic field generated by sources at 
observers can be computed through the top level functions getB and getH. 
Sources are magpylib source objects like Circular or Dipole. Observers are magpylib 
Sensor objects or simply sets (list, tuple, ndarray) of positions. The result will be 
an array of all possible source-observer-path combinations

'''